# Generated by Django 4.0.3 on 2022-04-01 16:11

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='format: required,max-100', max_length=100, verbose_name='category name')),
                ('slug', models.SlugField(help_text='format: required,letters,numbers,underscore, or hyphens', max_length=150, verbose_name='category safe URL')),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='format: true=category visisble', null=True, verbose_name='category visiblity')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='format: not required', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.category', verbose_name='parent of category')),
            ],
            options={
                'verbose_name': 'product category',
                'verbose_name_plural': 'product categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.CharField(help_text='format: required,unique', max_length=50, unique=True, verbose_name='product website id')),
                ('name', models.CharField(help_text='format: required,max-255', max_length=255, verbose_name='product name')),
                ('slug', models.SlugField(help_text='format: required,letters,numbers,underscore, or hyphens', max_length=150, verbose_name='product safe URL')),
                ('description', models.TextField(help_text='format: required', verbose_name='product description')),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='format: true=product visisble', null=True, verbose_name='product visiblity')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='format: Y-m-d H:M:S', verbose_name='date product created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='format: Y-m-d H:M:S', verbose_name='date product updated')),
                ('category', mptt.fields.TreeManyToManyField(to='inventory.category')),
            ],
        ),
    ]
