version: "3.8"

services:
  pgdb:
    container_name: pgdb_ecommerce
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  esearch:
    container_name: search
    image: elasticsearch:8.1.2
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=pa5is8an
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - 9200:9200
